name: Lint

on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  run-lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
      - name: install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
